blank_issues_enabled: false
contact_links:
  - name: Help/Support
    url: https://github.com/DRincs-Productions/daz-assert-ABFD-all-in-one/discussions/categories/q-a
    about: 'You had some problems during the installation or you are simply new to it. Ask me?'
