name: Request Upload Member
description: "Open gesture ticket if you want to become an Upload"
title: "[Member]"
labels: ["become a member"]
assignees: ["donrp"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe yourself
      description: Describe yourself. it may be helpful to add links of your accounts that show your work. And describe your experiences.
    validations:
      required: true
  - type: textarea
    id: language
    attributes:
      label: Why?
      description: Why do you want to help me?
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: "Agree to the terms"
      description: "[Terms](https://github.com/DRincs-Productions/ABFD/wiki/Upload#terms) and [Requirements](https://github.com/DRincs-Productions/ABFD/wiki/Upload#requirements). Project statements can have sexually oriented content and be used to create sex games."
      options:
        - label: "I acknowledge that I have read and agree to the Terms and Requirements. I declare that I am over 18 years of age." 
          required: true
